### ISSUE TITLE
css-validation-fixes

### ISSUE THREAD

**Issue by VanshitaGandhi** [VanshitaGandhi/css-validation-fixes#1]
I edited the name of the folder named CSS(uppercase) into css(lowercase) in the atom and can't find an option to rename it on the GitHub website.
Tried forking and cloning it again but it didn't make a difference.

@thomasjbradley

**Comment by thomasjbradley** [comment]
Git doesn’t actually recognize folders: only filenames.

The only way to get it to work is to rename `main.css` to something completely different: `dino.css`. Commit that. Then rename it back to `main.css`.

**Comment by VanshitaGandhi** [comment]
It worked, Thankyou! :) 
@thomasjbradley
